#!/usr/bin/env bash

prividium_host_bootstrap_usage() {
  cat <<'EOF'
Bootstrap the local Ansible controller on the evaluation VPS.

Usage:
  ./cli/prividium host bootstrap

Options:
  -h, --help  Show this help

Bootstrap creates ansible/.venv from the pinned runtime requirements and
writes a Gitignored one-host local inventory for the current user. It does not
install system packages, change SSH or firewall rules, install Docker, or
deploy the Prividium stack.
EOF
}

prividium_host_bootstrap_require_python() {
  prividium_require_commands "host bootstrap" python3
  if ! python3 -c \
    'import sys; raise SystemExit(0 if sys.version_info >= (3, 12) else 1)'
  then
    prividium_fail "host bootstrap requires Python 3.12 or newer"
  fi

  if [[ "$(uname -s)" == "Linux" ]] && ! /usr/bin/python3 -c 'import apt'; then
    prividium_fail \
      "host bootstrap requires python3-apt; run 'sudo apt-get update && sudo apt-get install --yes git python3-apt python3-venv', then rerun bootstrap"
  fi
}

prividium_host_bootstrap_requirements_satisfied() {
  local python_bin="$1"
  local requirements_file="$2"

  "$python_bin" -c '
from importlib import metadata
from pathlib import Path
import sys

for raw_line in Path(sys.argv[1]).read_text().splitlines():
    line = raw_line.strip()
    if not line or line.startswith("#"):
        continue
    name, separator, expected = line.partition("==")
    if not separator:
        raise SystemExit(1)
    try:
        actual = metadata.version(name)
    except metadata.PackageNotFoundError:
        raise SystemExit(1)
    if actual != expected:
        raise SystemExit(1)
' "$requirements_file"
}

prividium_host_bootstrap_install_controller() {
  local ansible_dir="${PRIVIDIUM_REPO_ROOT}/ansible"
  local requirements_file="${ansible_dir}/requirements.txt"
  local venv_dir="${ansible_dir}/.venv"
  local venv_python="${venv_dir}/bin/python"

  if [[ -L "$venv_dir" ]]; then
    prividium_fail "Ansible virtual environment must not be a symbolic link"
  fi
  if [[ ! -x "$venv_python" ]]; then
    printf "Creating the pinned Ansible environment...\n"
    if ! python3 -m venv "$venv_dir"; then
      prividium_fail \
        "could not create ansible/.venv; run 'sudo apt-get update && sudo apt-get install --yes git python3-apt python3-venv', then rerun bootstrap"
    fi
  fi
  if ! prividium_host_bootstrap_requirements_satisfied \
    "$venv_python" \
    "$requirements_file"
  then
    printf "Installing pinned Ansible into ansible/.venv...\n"
    "$venv_python" -m pip install \
      --disable-pip-version-check \
      --requirement "$requirements_file"
  fi
  if [[ ! -x "${venv_dir}/bin/ansible-inventory" ||
        ! -x "${venv_dir}/bin/ansible-playbook" ]]; then
    prividium_fail "pinned Ansible environment is incomplete after installation"
  fi
}

prividium_host_bootstrap_write_configuration() {
  local operator_user="$1"
  local inventory_file="${PRIVIDIUM_REPO_ROOT}/ansible/inventory/hosts.ini"
  local variables_file="${PRIVIDIUM_REPO_ROOT}/ansible/inventory/group_vars/all.yml"
  local inventory_tmp
  local variables_tmp

  if [[ -L "$inventory_file" || -L "$variables_file" ]]; then
    prividium_fail "generated Ansible configuration files must not be symbolic links"
  fi

  inventory_tmp=$(mktemp "${inventory_file}.tmp.XXXXXX")
  variables_tmp=$(mktemp "${variables_file}.tmp.XXXXXX")
  chmod 0600 "$inventory_tmp" "$variables_tmp"

  {
    printf "# Generated by ./cli/prividium host bootstrap.\n"
    printf "[prividium]\n"
    printf "sandbox-vps ansible_connection=local ansible_host=127.0.0.1"
    printf " ansible_user=%s\n\n" "$operator_user"
    printf "[prividium:vars]\n"
    printf "ansible_python_interpreter=/usr/bin/python3\n"
  } > "$inventory_tmp"

  {
    printf "%s\n" "---"
    printf "# Generated non-secret local host configuration.\n"
    printf "prividium_operator_user: %s\n" "$operator_user"
    printf "prividium_runtime_dir: /etc/prividium/runtime\n"
  } > "$variables_tmp"

  mv "$variables_tmp" "$variables_file"
  mv "$inventory_tmp" "$inventory_file"
}

prividium_host_bootstrap() {
  local current_user
  local inventory_file="${PRIVIDIUM_REPO_ROOT}/ansible/inventory/hosts.ini"
  local variables_file="${PRIVIDIUM_REPO_ROOT}/ansible/inventory/group_vars/all.yml"
  local show_help="false"

  while (( $# )); do
    case "$1" in
      -h|--help)
        show_help="true"
        shift
        ;;
      -*)
        prividium_fail "unknown host bootstrap option: $1"
        ;;
      *)
        prividium_fail "unexpected host bootstrap argument: $1"
        ;;
    esac
  done

  if [[ "$show_help" == "true" ]]; then
    prividium_host_bootstrap_usage
    return
  fi

  current_user=$(id -un)
  if [[ "$current_user" == "root" ]]; then
    prividium_fail \
      "host bootstrap must run as a normal passwordless-sudo operator, not root"
  fi
  if [[ ! "$current_user" =~ ^[a-z_][a-z0-9_-]{0,31}$ ]]; then
    prividium_fail "current user is not a supported Linux username"
  fi
  prividium_host_bootstrap_require_python

  if [[ -L "$inventory_file" || -L "$variables_file" ]]; then
    prividium_fail "generated Ansible configuration files must not be symbolic links"
  fi
  if [[ -e "$inventory_file" || -e "$variables_file" ]]; then
    if [[ ! -f "$inventory_file" || ! -f "$variables_file" ]]; then
      prividium_fail \
        "host bootstrap is incomplete; expected both ansible/inventory/hosts.ini and ansible/inventory/group_vars/all.yml"
    fi
    prividium_host_bootstrap_install_controller
    printf "Prividium host bootstrap is already configured; existing files were preserved.\n\n"
    printf "Next: ./cli/prividium host preflight\n"
    return
  fi

  prividium_host_bootstrap_write_configuration "$current_user"
  prividium_host_bootstrap_install_controller

  printf "\nPrividium host bootstrap complete.\n"
  printf "Generated: ansible/inventory/hosts.ini\n"
  printf "Generated: ansible/inventory/group_vars/all.yml\n"
  printf "Installed: ansible/.venv\n\n"
  printf "No system packages, SSH settings, firewall rules, or Docker state changed.\n"
  printf "Next: ./cli/prividium host preflight\n"
}
