---
host_packages_apply_safe_upgrade: true
host_packages_cache_valid_time_seconds: 3600
host_packages_required:
  - age
  - ca-certificates
  - chrony
  - curl
  - git
  - gnupg
  - jq
  - openssl
  - python3-apt
  - python3-debian
  - unattended-upgrades
